In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
seri = pd.Series([13,15,12,87])

In [5]:
seri

0    13
1    15
2    12
3    87
dtype: int64

In [6]:
type(seri)

pandas.core.series.Series

In [7]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [8]:
seri.dtype

dtype('int64')

In [9]:
seri.ndim

1

In [10]:
seri.size

4

In [11]:
seri.head(3)

0    13
1    15
2    12
dtype: int64

In [12]:
seri.tail

<bound method NDFrame.tail of 0    13
1    15
2    12
3    87
dtype: int64>

In [13]:
#index isimlendirmesi

In [14]:
pd.Series([99,22,332,5,97])

0     99
1     22
2    332
3      5
4     97
dtype: int64

In [15]:
pd.Series([99,22,332,5,97], index = [1,3,5,6,7])

1     99
3     22
5    332
6      5
7     97
dtype: int64

In [16]:
pd.Series([99,22,332,5,97], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d      5
e     97
dtype: int64

In [17]:
seri = pd.Series([99,22,332,5,97], index = ["a","b","c","d","e"])

In [18]:
seri["c"]

332

In [19]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [20]:
#sözlük uzerinden liste oluşturma

In [22]:
sozluk = pd.Series({"reg":10, "log":11, "cart": 12})

In [23]:
sozluk

reg     10
log     11
cart    12
dtype: int64

In [24]:
#or

In [25]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [26]:
seri = pd.Series(sozluk)

In [27]:
seri

reg     10
log     11
cart    12
dtype: int64

In [28]:
#iki seriyi birleştirme

In [29]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [31]:
#eleman işlemleri

In [33]:
import numpy as np

In [34]:
a = np.array([1,2,33,444,76])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     76
dtype: int32

In [35]:
seri = pd.Series([121,200,150,99], index =["reg","loj","cart","rf"])

In [36]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [37]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [38]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [39]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [40]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [41]:
"reg" in seri

True

In [42]:
"b" in seri

False

In [43]:
#fancy eleman

In [44]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [45]:
seri["reg"] = 131

In [46]:
seri

reg     131
loj     200
cart    150
rf       99
dtype: int64

In [47]:
seri["reg":"loj"]

reg    131
loj    200
dtype: int64

In [48]:
#pandas DataFrame Oluşturma

In [49]:
 l = [1,2,39,56,98]

In [50]:
l

[1, 2, 39, 56, 98]

In [51]:
pd.DataFrame(l, columns =["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             56
4             98

In [52]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [54]:
#df isimlendirme

In [55]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [56]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [57]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [58]:
df.columns = ("deg1","deg2","deg3")

In [59]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [60]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [61]:
df.ndim


2

In [62]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
type(df.values)

numpy.ndarray

In [64]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [65]:
a  = np.array([1,2,3,4,5])

In [66]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

In [67]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [68]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [69]:
sozluk

{'var1': array([1, 7, 2, 2, 0]),
 'var2': array([8, 2, 8, 9, 4]),
 'var3': array([1, 1, 6, 6, 5])}

In [70]:
df = pd.DataFrame(sozluk)

In [71]:
df

var1  var2  var3
0     1     8     1
1     7     2     1
2     2     8     6
3     2     9     6
4     0     4     5

In [72]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [73]:
df.index = ["a","b","c","d","e"]

In [74]:
df

var1  var2  var3
a     1     8     1
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [75]:
#silme

In [76]:
df.drop("a",axis = 0)

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [77]:
df

var1  var2  var3
a     1     8     1
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [78]:
df.drop("a", axis = 0, inplace = True)

In [79]:
df

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [80]:
# inplace silme işlemini df üzerinde kalıcı hale getirdi

In [82]:
l = ["c","e"]

In [83]:
df.drop(l, axis = 0)

var1  var2  var3
b     7     2     1
d     2     9     6

In [84]:
#değişkenler için

In [85]:
df

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [86]:
l = ["var1","var4","var2"]

In [87]:
for i in l:
    print(i in df)

True
False
True


In [88]:
df 

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [91]:
df["var4"] = df["var1"] / df["var2"]

In [92]:
df

var1  var2  var3      var4
b     7     2     1  3.500000
c     2     8     6  0.250000
d     2     9     6  0.222222
e     0     4     5  0.000000

In [93]:
df.drop("var4",axis = 1)

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [94]:
df

var1  var2  var3      var4
b     7     2     1  3.500000
c     2     8     6  0.250000
d     2     9     6  0.222222
e     0     4     5  0.000000

In [95]:
df.drop("var4", axis = 1, inplace = True)

In [96]:
df

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [97]:
l=["var1","var2"]

In [98]:
df.drop(l, axis = 1)

var3
b     1
c     6
d     6
e     5

In [99]:
df

var1  var2  var3
b     7     2     1
c     2     8     6
d     2     9     6
e     0     4     5

In [100]:
#gözlem ve değişken seçimi: loc & iloc

In [101]:
m = np.random.randint(1,30,size = (10,3))

In [102]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     8    11     8
1    12     8    18
2    12    22    28
3    14    25    26
4    15    19    16
5    18    20     5
6    17     3     8
7    19    18     6
8    23    27    20
9    15    28     8

In [104]:
#loc: tanımlandığı şekliyle seçim yapmak için kullanılır

In [105]:
df.loc[0:3]

var1  var2  var3
0     8    11     8
1    12     8    18
2    12    22    28
3    14    25    26

In [106]:
#iloc: alışık olduğumuz indexleme mantığıyla seçim yapar

In [107]:
df.iloc[0:3]

var1  var2  var3
0     8    11     8
1    12     8    18
2    12    22    28

In [108]:
df.iloc[0,0]

8

In [109]:
df.iloc[:3,:2]

var1  var2
0     8    11
1    12     8
2    12    22

In [110]:
df.loc[0:3,"var3"]

0     8
1    18
2    28
3    26
Name: var3, dtype: int32

In [111]:
df

var1  var2  var3
0     8    11     8
1    12     8    18
2    12    22    28
3    14    25    26
4    15    19    16
5    18    20     5
6    17     3     8
7    19    18     6
8    23    27    20
9    15    28     8

In [115]:
df.iloc[0:3] ["var3"]

0     8
1    18
2    28
Name: var3, dtype: int32

In [116]:
df["var1"]

0     8
1    12
2    12
3    14
4    15
5    18
6    17
7    19
8    23
9    15
Name: var1, dtype: int32

In [117]:
df["var1"][0:2]

0     8
1    12
Name: var1, dtype: int32

In [118]:
df

var1  var2  var3
0     8    11     8
1    12     8    18
2    12    22    28
3    14    25    26
4    15    19    16
5    18    20     5
6    17     3     8
7    19    18     6
8    23    27    20
9    15    28     8

In [119]:
df[0:2]

var1  var2  var3
0     8    11     8
1    12     8    18

In [120]:
df[0:2][["var1","var2"]]

var1  var2
0     8    11
1    12     8

In [128]:
df[df.var1 > 13]

var1  var2  var3
1    12     8    18
2    12    22    28
3    14    25    26
4    15    19    16
8    23    27    20

In [132]:
df[(df.var1 > 13) & (df.var3 < 10)]

var1  var2  var3
5    18    20     5
6    17     3     8
7    19    18     6
9    15    28     8

In [135]:
df[(df.var1 > 13)] [["var1","var2"]]

var1  var2
3    14    25
4    15    19
5    18    20
6    17     3
7    19    18
8    23    27
9    15    28

In [136]:
m = np.random.randint(1,30,size = (10,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    10     8    16
1    21    10     5
2    29    15     8
3     7    22    28
4    28    19    15
5    24    19    26
6    10    27     2
7    13    16     8
8    25     5     4
9    29    12    24

In [137]:
df2 = df1 + 99

In [138]:
df2

var1  var2  var3
0   109   107   115
1   120   109   104
2   128   114   107
3   106   121   127
4   127   118   114
5   123   118   125
6   109   126   101
7   112   115   107
8   124   104   103
9   128   111   123

In [139]:
pd.concat([df1,df2])

var1  var2  var3
0    10     8    16
1    21    10     5
2    29    15     8
3     7    22    28
4    28    19    15
5    24    19    26
6    10    27     2
7    13    16     8
8    25     5     4
9    29    12    24
0   109   107   115
1   120   109   104
2   128   114   107
3   106   121   127
4   127   118   114
5   123   118   125
6   109   126   101
7   112   115   107
8   124   104   103
9   128   111   123

In [140]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0     10     8    16
1     21    10     5
2     29    15     8
3      7    22    28
4     28    19    15
5     24    19    26
6     10    27     2
7     13    16     8
8     25     5     4
9     29    12    24
10   109   107   115
11   120   109   104
12   128   114   107
13   106   121   127
14   127   118   114
15   123   118   125
16   109   126   101
17   112   115   107
18   124   104   103
19   128   111   123

In [144]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [150]:
df2.columns = ["var1","var2","deg3"]

In [147]:
df2

var1  var2  deg3
0   109   107   115
1   120   109   104
2   128   114   107
3   106   121   127
4   127   118   114
5   123   118   125
6   109   126   101
7   112   115   107
8   124   104   103
9   128   111   123

In [148]:
df1

var1  var2  var3
0    10     8    16
1    21    10     5
2    29    15     8
3     7    22    28
4    28    19    15
5    24    19    26
6    10    27     2
7    13    16     8
8    25     5     4
9    29    12    24

In [149]:
pd.concat([df1, df2])

var1  var2  var3   deg3
0    10     8  16.0    NaN
1    21    10   5.0    NaN
2    29    15   8.0    NaN
3     7    22  28.0    NaN
4    28    19  15.0    NaN
5    24    19  26.0    NaN
6    10    27   2.0    NaN
7    13    16   8.0    NaN
8    25     5   4.0    NaN
9    29    12  24.0    NaN
0   109   107   NaN  115.0
1   120   109   NaN  104.0
2   128   114   NaN  107.0
3   106   121   NaN  127.0
4   127   118   NaN  114.0
5   123   118   NaN  125.0
6   109   126   NaN  101.0
7   112   115   NaN  107.0
8   124   104   NaN  103.0
9   128   111   NaN  123.0

In [151]:
pd.concat([df1, df2], join = "inner")

var1  var2
0    10     8
1    21    10
2    29    15
3     7    22
4    28    19
5    24    19
6    10    27
7    13    16
8    25     5
9    29    12
0   109   107
1   120   109
2   128   114
3   106   121
4   127   118
5   123   118
6   109   126
7   112   115
8   124   104
9   128   111