In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [11]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4, (3,4))

array([[ 7.84331199,  8.05957008,  9.63963938, 17.23778928],
       [11.44408477,  5.06439266,  6.65185183, 10.26666819],
       [14.42905931, 15.54120963, 12.4753702 ,  8.45859949]])

In [18]:
np.random.randint(0,10, (3,3))

array([[9, 8, 6],
       [0, 4, 6],
       [1, 6, 7]])

In [21]:
a = np.random.randint(10, size = 10)

In [22]:
a.ndim

1

In [24]:
a.shape

(10,)

In [25]:
a.size

10

In [26]:
a.dtype

dtype('int32')

In [27]:
b = np.random.randint(10, size = (3,5))

In [28]:
b

array([[2, 2, 2, 4, 2],
       [2, 0, 2, 7, 3],
       [3, 2, 9, 9, 8]])

In [29]:
b.ndim

2

In [30]:
b.shape

(3, 5)

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a = np.arange(1,10)

In [35]:
a.ndim

1

In [37]:
b = a.reshape((1,9))

In [38]:
b.ndim

2

In [39]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [41]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [42]:
z = np.array([7,8,9])

In [43]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a = np.array([[1,2,3], [4,5,6]])

In [45]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([a,a], axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
x = np.array([1,2,3,99,99,3,2,1])

In [48]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [49]:
a,b,c = np.split(x, [3,5])

In [50]:
a

array([1, 2, 3])

In [51]:
b

array([99, 99])

In [52]:
c

array([3, 2, 1])

In [1]:
#iki boyutlu ayırma

In [54]:
m = np.arange(16).reshape(4,4)

In [55]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
ust, alt = np.vsplit(m, [2])

In [61]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
sag , sol = np.hsplit(m, [2])

In [66]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [67]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [69]:
v = np.array([2,1,4,3,5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [71]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [72]:
v

array([2, 1, 4, 3, 5])

In [73]:
v.sort()

In [74]:
v

array([1, 2, 3, 4, 5])

In [75]:
#iki boyutlu array sıralama

In [81]:
 m = np.random.normal(20,5, (3,3))
m

array([[ 1.60965106, 12.55140632,  9.96908227],
       [19.29964218, 16.32937483, 26.59687967],
       [22.73278246, 13.72691452, 28.10275694]])

In [82]:
np.sort(m, axis =1)

array([[ 1.60965106,  9.96908227, 12.55140632],
       [16.32937483, 19.29964218, 26.59687967],
       [13.72691452, 22.73278246, 28.10275694]])

In [83]:
np.sort(m, axis =0)

array([[ 1.60965106, 12.55140632,  9.96908227],
       [19.29964218, 13.72691452, 26.59687967],
       [22.73278246, 16.32937483, 28.10275694]])

In [84]:
a = np.random.randint(10, size =10)
a

array([7, 7, 5, 3, 3, 9, 0, 3, 8, 7])

In [85]:
a[0]

7

In [86]:
a[0] = 100

In [87]:
a

array([100,   7,   5,   3,   3,   9,   0,   3,   8,   7])

In [88]:
m = np.random.randint(10,size = (3,5))
m

array([[2, 9, 1, 4, 5],
       [5, 4, 1, 9, 4],
       [5, 8, 4, 5, 8]])

In [89]:
m[0,0]

2

In [90]:
m[1,1]

4

In [91]:
m[1,4]

4

In [92]:
m[1,4] = 13

In [93]:
m

array([[ 2,  9,  1,  4,  5],
       [ 5,  4,  1,  9, 13],
       [ 5,  8,  4,  5,  8]])

In [94]:
m[1,4] = 2.2

In [95]:
m

array([[2, 9, 1, 4, 5],
       [5, 4, 1, 9, 2],
       [5, 8, 4, 5, 8]])

In [96]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [97]:
a[0:3]

array([20, 21, 22])

In [98]:
a[1::2]

array([21, 23, 25, 27, 29])

In [99]:
a[0::3]

array([20, 23, 26, 29])

In [100]:
#iki boyutlu slice işlemleri

In [101]:
m = np.random.randint(10, size = (5,5))
m

array([[6, 5, 2, 4, 9],
       [4, 3, 0, 5, 8],
       [6, 2, 0, 5, 4],
       [8, 9, 8, 1, 2],
       [1, 0, 5, 7, 3]])

In [102]:
m[:,0]

array([6, 4, 6, 8, 1])

In [103]:
m[:,3]

array([4, 5, 5, 1, 7])

In [104]:
m[0,:]

array([6, 5, 2, 4, 9])

In [105]:
m[0]

array([6, 5, 2, 4, 9])

In [106]:
m[1]

array([4, 3, 0, 5, 8])

In [109]:
m[0:2, 0:3]

array([[6, 5, 2],
       [4, 3, 0]])

In [111]:
m[:,0:2]

array([[6, 5],
       [4, 3],
       [6, 2],
       [8, 9],
       [1, 0]])

In [112]:
m[1:3, 0:2]

array([[4, 3],
       [6, 2]])

In [113]:
m

array([[6, 5, 2, 4, 9],
       [4, 3, 0, 5, 8],
       [6, 2, 0, 5, 4],
       [8, 9, 8, 1, 2],
       [1, 0, 5, 7, 3]])

In [114]:
a = np.random.randint(10, size = (5,5))

In [115]:
a

array([[0, 4, 5, 8, 1],
       [6, 6, 8, 7, 3],
       [1, 2, 6, 8, 7],
       [4, 5, 5, 8, 1],
       [2, 6, 9, 2, 3]])

In [116]:
alt_a = a[0:3, 0:2]

In [117]:
alt_a

array([[0, 4],
       [6, 6],
       [1, 2]])

In [118]:
alt_a[0,0] = 9999
alt_a[1,1] = 5555

In [119]:
alt_a

array([[9999,    4],
       [   6, 5555],
       [   1,    2]])

In [120]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 1, 7, 9, 5],
       [6, 4, 9, 1, 9],
       [8, 8, 7, 9, 7],
       [7, 6, 3, 1, 1],
       [8, 0, 3, 9, 5]])

In [121]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[3, 1],
       [6, 4],
       [8, 8]])

In [122]:
alt_b[0,0] = 9999
alt_b

array([[9999,    1],
       [   6,    4],
       [   8,    8]])

In [123]:
m

array([[3, 1, 7, 9, 5],
       [6, 4, 9, 1, 9],
       [8, 8, 7, 9, 7],
       [7, 6, 3, 1, 1],
       [8, 0, 3, 9, 5]])

In [124]:
#fancy index 

In [125]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [126]:
v[1]

3

In [127]:
[v[1], v[3]]

[3, 9]

In [128]:
getir = [1,3,5,6]

In [129]:
v[getir]

array([ 3,  9, 15, 18])

In [130]:
#yukarıdaki fancy index oluyor

In [131]:
#iki boyutta fancy index

In [132]:
m = np.arange(9).reshape((3,3))

In [133]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [135]:
m[satir, sutun]

array([1, 5])

In [136]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
m[0, [1,2]]

array([1, 2])

In [141]:
#slice ile fancy

In [142]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [143]:
#koşullu eleman işlemleri

In [144]:
v = np.array([1,2,3,4,5])

In [145]:
v > 5

array([False, False, False, False, False])

In [146]:
v < 3

array([ True,  True, False, False, False])

In [147]:
v[v<3]

array([1, 2])

In [148]:
v [v>3]

array([4, 5])

In [150]:
v[v<=4]

array([1, 2, 3, 4])

In [151]:
v

array([1, 2, 3, 4, 5])

In [152]:
v*2

array([ 2,  4,  6,  8, 10])

In [153]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [154]:
v*5/10-2

array([-1.5, -1. , -0.5,  0. ,  0.5])

In [155]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [156]:
v

array([1, 2, 3, 4, 5])

In [157]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [159]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [160]:
np.add(v,2)

array([3, 4, 5, 6, 7])

In [161]:
np.power(v, 10)

array([      1,    1024,   59049, 1048576, 9765625], dtype=int32)

In [162]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [164]:
np.absolute(np.array([-5]))

array([5])

In [165]:
np.sin(360)

0.9589157234143065

In [166]:
np.cos(180)

-0.5984600690578581

In [167]:
v = np.array([1,2,3])

In [168]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [169]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [172]:
v.min()

1